name: 'preview'
on: # rebuild any PRs and main branch changes
  pull_request:
    # use default types + closed event type
    types: [opened, synchronize, reopened, closed]

jobs:
  preview: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: preview_step
        name: test pr-preview
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vercel_token: 14O4V8qD7ci0K6w3uxLMa80t
          teardown: 'true'
          dist: public/preview
          build: |
            mkdir -p public/preview
            npm install -g yarn
            yarn
            yarn build-preview -- public/preview
      - name: Get the output url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"
  preview2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: preview_action
        name: test pr-preview
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vercel_token: 14O4V8qD7ci0K6w3uxLMa80t
          teardown: 'true'
          dist: public/preview2
          build: |
            mkdir -p public/preview2
            npm install -g yarn
            yarn
            yarn build-preview -- public/preview2
      - name: Get the output url
        run: echo "url => ${{ steps.preview_action.outputs.preview_url }}"
  preview3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: preview_action
        name: test pr-preview
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vercel_token: 14O4V8qD7ci0K6w3uxLMa80t
          preview_path: '/teste/'
          preview_url: '{{repoOwner}}-{{repoName}}-{{job}}-pr-{{prNumber}}'
          teardown: 'true'
          dist: public/preview3
          build: |
            mkdir -p public/preview3/teste/
            npm install -g yarn
            yarn
            yarn build-preview -- public/preview3
            cp ./public/preview3/index.html ./public/preview3/teste/index.html
      - name: Get the output url
        run: echo "url => ${{ steps.preview_action.outputs.preview_url }}"
  preview4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: preview_action
        name: test pr-preview
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          preview_url: '{{repoOwner}}-{{repoName}}-{{job}}-pr-{{prNumber}}'
          teardown: 'true'
          dist: public/preview3
          build: |
            mkdir -p public/preview3/teste/
            npm install -g yarn
            yarn
            yarn build-preview -- public/preview3
            cp ./public/preview3/index.html ./public/preview3/teste/index.html
      - name: Get the output url
        run: echo "url => ${{ steps.preview_action.outputs.preview_url }}"
